from __future__ import annotations

from toyts.ptbxl import ptbxl_all_codes, ptbxl_codes_by_group, ptbxl_group_indices, ptbxl_rhythm_codes


def test_ptbxl_scp_loader_all_codes() -> None:
    assert ptbxl_all_codes() == [
        "NDT",
        "NST_",
        "DIG",
        "LNGQT",
        "NORM",
        "IMI",
        "ASMI",
        "LVH",
        "LAFB",
        "ISC_",
        "IRBBB",
        "1AVB",
        "IVCD",
        "ISCAL",
        "CRBBB",
        "CLBBB",
        "ILMI",
        "LAO/LAE",
        "AMI",
        "ALMI",
        "ISCIN",
        "INJAS",
        "LMI",
        "ISCIL",
        "LPFB",
        "ISCAS",
        "INJAL",
        "ISCLA",
        "RVH",
        "ANEUR",
        "RAO/RAE",
        "EL",
        "WPW",
        "ILBBB",
        "IPLMI",
        "ISCAN",
        "IPMI",
        "SEHYP",
        "INJIN",
        "INJLA",
        "PMI",
        "3AVB",
        "INJIL",
        "2AVB",
        "ABQRS",
        "PVC",
        "STD_",
        "VCLVH",
        "QWAVE",
        "LOWT",
        "NT_",
        "PAC",
        "LPR",
        "INVT",
        "LVOLT",
        "HVOLT",
        "TAB_",
        "STE_",
        "PRC(S)",
        "SR",
        "AFIB",
        "STACH",
        "SARRH",
        "SBRAD",
        "PACE",
        "SVARR",
        "BIGU",
        "AFLT",
        "SVTAC",
        "PSVT",
        "TRIGU",
    ]


def test_ptbxl_scp_loader_rhythm_codes() -> None:
    assert ptbxl_rhythm_codes() == [
        "SR",
        "AFIB",
        "STACH",
        "SARRH",
        "SBRAD",
        "PACE",
        "SVARR",
        "BIGU",
        "AFLT",
        "SVTAC",
        "PSVT",
        "TRIGU",
    ]


def test_ptbxl_scp_loader_group_codes() -> None:
    assert ptbxl_codes_by_group("diagnostic") == [
        "NDT",
        "NST_",
        "DIG",
        "LNGQT",
        "NORM",
        "IMI",
        "ASMI",
        "LVH",
        "LAFB",
        "ISC_",
        "IRBBB",
        "1AVB",
        "IVCD",
        "ISCAL",
        "CRBBB",
        "CLBBB",
        "ILMI",
        "LAO/LAE",
        "AMI",
        "ALMI",
        "ISCIN",
        "INJAS",
        "LMI",
        "ISCIL",
        "LPFB",
        "ISCAS",
        "INJAL",
        "ISCLA",
        "RVH",
        "ANEUR",
        "RAO/RAE",
        "EL",
        "WPW",
        "ILBBB",
        "IPLMI",
        "ISCAN",
        "IPMI",
        "SEHYP",
        "INJIN",
        "INJLA",
        "PMI",
        "3AVB",
        "INJIL",
        "2AVB",
    ]
    assert ptbxl_codes_by_group("form") == [
        "NDT",
        "NST_",
        "DIG",
        "LNGQT",
        "ABQRS",
        "PVC",
        "STD_",
        "VCLVH",
        "QWAVE",
        "LOWT",
        "NT_",
        "PAC",
        "LPR",
        "INVT",
        "LVOLT",
        "HVOLT",
        "TAB_",
        "STE_",
        "PRC(S)",
    ]


def test_ptbxl_group_indices_match_groups() -> None:
    scp_codes = ptbxl_all_codes()
    groups = ptbxl_group_indices(scp_codes=scp_codes)
    assert [scp_codes[i] for i in groups["rhythm"]] == ptbxl_codes_by_group("rhythm")
    assert [scp_codes[i] for i in groups["diagnostic"]] == ptbxl_codes_by_group("diagnostic")
    assert [scp_codes[i] for i in groups["form"]] == ptbxl_codes_by_group("form")
